export enum ReportTargetType {
  PROPERTY = 'PROPERTY',
  USER = 'USER',
  REVIEW = 'REVIEW',
  BOOKING = 'BOOKING'
}

export enum ReportType {
  INAPPROPRIATE_CONTENT = 'INAPPROPRIATE_CONTENT',
  MISLEADING_INFORMATION = 'MISLEADING_INFORMATION',
  FAKE_LISTING = 'FAKE_LISTING',
  SCAM = 'SCAM',
  HARASSMENT = 'HARASSMENT',
  DISCRIMINATION = 'DISCRIMINATION',
  POLICY_VIOLATION = 'POLICY_VIOLATION',
  OTHER = 'OTHER'
}

export enum ReportStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED'
}