"use client"

import React from "react"
import { cn } from "@/lib/utils"
import {
  // Navigation & Core
  LayoutDashboard,
  Home,
  Menu,
  X,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowUpDown,
  ArrowUp,
  ArrowDown,
  MoreHorizontal,
  MoreVertical,
  Plus,
  Minus,
  Search,
  Filter,
  Settings,
  User,
  LogOut,
  LogIn,
  Bell,
  Eye,
  EyeOff,

  // Inventory Management
  Package,
  Box,
  Bed,
  BedSingle,
  BedDouble,
  Hotel,
  Building,
  Building2,
  MapPin,
  Wifi,
  Snowflake,
  Tv,
  Droplets,
  Coffee,
  Utensils,
  Car,
  Bike,
  Dumbbell,
  Wrench,
  Hammer,

  // Booking & Reservations
  Calendar,
  CalendarDays,
  Clock,
  Watch,
  CheckCircle,
  XCircle,
  AlertCircle,
  Info,
  Star,
  Heart,
  Bookmark,
  Tag,
  Ticket,
  CreditCard,
  DollarSign,
  IndianRupee,
  Euro,
  PoundSterling,

  // Guest Services
  Users,
  UserCheck,
  UserPlus,
  UserMinus,
  UserX,
  Phone,
  Mail,
  MessageSquare,
  MessageCircle,
  Send,
  Reply,
  Forward,
  Camera,
  Video,
  Headphones,
  Gift,
  Award,
  Trophy,
  Medal,

  // Financial Management
  Wallet,
  Banknote,
  Coins,
  TrendingUp,
  TrendingDown,
  BarChart,
  BarChart3,
  PieChart,
  LineChart,
  Activity,
  Target,
  Percent,
  Calculator,
  Receipt,
  FileText,
  FileSpreadsheet,
  Download,
  Upload,
  Printer,
  Share,

  // Staff Management
  GraduationCap,
  BookOpen,
  Shield,
  Lock,
  Unlock,
  Key,
  Fingerprint,
  QrCode,
  Smartphone,
  Tablet,
  Monitor,
  Laptop,

  // Reports & Analytics
  FileText as ReportIcon,
  Download as ExportIcon,
  Upload as ImportIcon,
  Share as ShareIcon,
  Printer as PrintIcon,
  Mail as EmailReportIcon,

  // Communication
  MessageSquare as ChatIcon,
  MessageCircle as MessageIcon,
  Phone as PhoneIcon,
  Mail as EmailIcon2,
  Send as SendIcon,
  Reply as ReplyIcon,
  Forward as ForwardIcon,
  Camera as CameraIcon,
  Video as VideoIcon,
  Headphones as HeadphonesIcon,

  // Notifications
  Bell as NotificationIcon,
  AlertCircle as AlertIcon,
  Info as InfoIcon,
  CheckCircle as SuccessIcon,
  XCircle as ErrorIcon,
  Star as StarIcon,
  Heart as HeartIcon,
  Bookmark as BookmarkIcon,

  // Actions
  Edit,
  Trash2,
  Copy,
  Save,
  RefreshCw,
  RotateCcw,
  RotateCw,
  ZoomIn,
  ZoomOut,
  Maximize,
  Minimize,
  Move,
  Crop,
  Scissors,

  // Status & Feedback
  Check,
  Circle,
  Square,
  Triangle,
  Hexagon,
  Octagon,

  // Time & Date
  Clock as TimeIcon2,
  Calendar as DateIcon,
  CalendarDays as DaysIcon,
  Watch as WatchIcon,
  Timer,
  Sunrise,
  Sunset,
  Moon,
  Sun,

  // Location & Travel
  MapPin as LocationIcon2,
  Navigation,
  Compass,
  Globe,
  Map,
  Flag,
  Anchor,
  Plane,
  Train,
  Bus,
  Car as CarIcon,
  Bike as BikeIcon,
  Ship,

  // Technology
  Wifi as WifiIcon,
  Bluetooth,
  Signal,
  Battery,
  Power,
  Zap,
  Cpu,
  HardDrive,
  Database,
  Server,
  Cloud,
  CloudRain,
  CloudLightning,
  CloudSnow,

  // Business & Commerce
  ShoppingCart,
  ShoppingBag,
  Store,
  Package as PackageIcon,
  Truck,
  Box as BoxIcon,
  Archive,
  Folder,
  FolderOpen,
  File,
  FileText as DocumentIcon,
  FileImage,
  FileVideo,
  FileAudio,
  FileCode,

  // Security & Privacy
  Shield as SecurityIcon,
  Lock as LockIcon,
  Unlock as UnlockIcon,
  Key as KeyIcon,
  Fingerprint as FingerprintIcon,
  QrCode as QrCodeIcon,
  Eye as ViewIcon,
  EyeOff as HideIcon,
  UserCheck as VerifyIcon,
  UserX as BlockIcon,

  // Health & Wellness
  Heart as HealthIcon,
  Activity as FitnessIcon,
  Dumbbell as GymIcon,
  Coffee as CoffeeIcon,
  Utensils as FoodIcon,
  Wine,
  Beer,
  Pill,
  Stethoscope,
  Thermometer,

  // Entertainment
  Tv as TvIcon,
  Radio,
  Headphones as AudioIcon,
  Speaker,
  Volume,
  VolumeX,
  Volume1,
  Volume2,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Shuffle,
  Repeat,
  Music,
  Video as VideoIcon2,
  Camera as CameraIcon2,
  Image,
  Film,
  Dice1,
  Puzzle,

  // Weather & Environment
  Sun as SunIcon,
  Moon as MoonIcon,
  Cloud as CloudIcon,
  CloudRain as RainIcon,
  CloudSnow as SnowIcon,
  CloudLightning as LightningIcon,
  Wind,
  Thermometer as TempIcon,
  Droplets as WaterIcon,
  Umbrella,
  Snowflake as SnowflakeIcon,
  Leaf,
  Trees,
  Flower,

  // Transportation
  Car as CarIcon2,
  Bike as BikeIcon2,
  Bus as BusIcon,
  Train as TrainIcon,
  Plane as PlaneIcon,
  Ship as ShipIcon,
  Truck as TruckIcon,

  // Communication & Social
  MessageSquare as MessageIcon2,
  MessageCircle as ChatIcon2,
  Phone as PhoneIcon2,
  Mail as MailIcon,
  Send as SendIcon2,
  Reply as ReplyIcon2,
  Forward as ForwardIcon2,
  Share as ShareIcon2,
  Link,
  Link2,
  ExternalLink,
  AtSign,
  Hash,

  // Development & Tools
  Code,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  GitCompare,
  GitFork,
  Terminal,
  Command,
  Cpu as CpuIcon,
  HardDrive as StorageIcon,
  Database as DatabaseIcon,
  Server as ServerIcon,
  Cloud as CloudIcon2,
  Wifi as NetworkIcon,
  Bluetooth as BluetoothIcon,
  Signal as SignalIcon,
  Battery as BatteryIcon,
  Power as PowerIcon,
  Zap as ZapIcon,

  // Miscellaneous
  HelpCircle,
  Info as InfoIcon2,
  AlertCircle as AlertIcon2,
  CheckCircle as CheckIcon,
  XCircle as XIcon,
  Star as StarIcon2,
  Heart as HeartIcon2,
  Bookmark as BookmarkIcon2,
  Flag as FlagIcon,
  Award as AwardIcon,
  Trophy as TrophyIcon,
  Medal as MedalIcon,
  Gift as GiftIcon,
  Package as GiftBoxIcon,
  Box as BoxIcon2,
  Archive as ArchiveIcon,
  Folder as FolderIcon,
  File as FileIcon,
  Image as ImageIcon,
  Video as VideoIcon3,
  Code as CodeIcon,
  Terminal as TerminalIcon,
  Command as CommandIcon,
  GitBranch as GitIcon,
  GitCommit as CommitIcon2,
  GitMerge as MergeIcon2,
  GitPullRequest as PullRequestIcon,
  GitCompare as CompareIcon2,
  GitFork as ForkIcon2,
  Database as DataIcon,
  Server as ServerIcon2,
  Cloud as CloudIcon3,
  Wifi as WifiIcon2,
  Bluetooth as BluetoothIcon2,
  Signal as SignalIcon2,
  Battery as BatteryIcon2,
  Power as PowerIcon2,
  Zap as ZapIcon2,
  Cpu as CpuIcon2,
  HardDrive as HardDriveIcon,
  Database as DatabaseIcon2,
  Server as ServerIcon3,
  Cloud as CloudIcon4,
  Wifi as WifiIcon3,
  Bluetooth as BluetoothIcon3,
  Signal as SignalIcon3,
  Battery as BatteryIcon3,
  Power as PowerIcon3,
  Zap as ZapIcon3,
} from "lucide-react"

// Icon Library Interface
interface IconProps {
  size?: number
  className?: string
  color?: string
  strokeWidth?: number
}

// Icon Library Component
interface IconLibraryProps extends IconProps {
  name: string
  variant?: "outline" | "filled" | "duotone"
}

// Icon mapping
const iconMap: Record<string, React.ComponentType<IconProps>> = {
  // Navigation & Core
  dashboard: LayoutDashboard,
  home: Home,
  menu: Menu,
  close: X,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "arrow-up-down": ArrowUpDown,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "more-horizontal": MoreHorizontal,
  "more-vertical": MoreVertical,
  plus: Plus,
  minus: Minus,
  search: Search,
  filter: Filter,
  settings: Settings,
  user: User,
  logout: LogOut,
  login: LogIn,
  bell: Bell,
  eye: Eye,
  "eye-off": EyeOff,

  // Inventory Management
  package: Package,
  box: Box,
  bed: Bed,
  "bed-single": BedSingle,
  "bed-double": BedDouble,
  hotel: Hotel,
  building: Building,
  "building-2": Building2,
  "map-pin": MapPin,
  wifi: Wifi,
  snowflake: Snowflake,
  tv: Tv,
  droplets: Droplets,
  coffee: Coffee,
  utensils: Utensils,
  car: Car,
  bike: Bike,
  dumbbell: Dumbbell,
  wrench: Wrench,
  hammer: Hammer,

  // Booking & Reservations
  calendar: Calendar,
  "calendar-days": CalendarDays,
  clock: Clock,
  watch: Watch,
  "check-circle": CheckCircle,
  "x-circle": XCircle,
  "alert-circle": AlertCircle,
  info: Info,
  star: Star,
  heart: Heart,
  bookmark: Bookmark,
  tag: Tag,
  ticket: Ticket,
  "credit-card": CreditCard,
  "dollar-sign": DollarSign,
  "indian-rupee": IndianRupee,
  euro: Euro,
  "pound-sterling": PoundSterling,

  // Guest Services
  users: Users,
  "user-check": UserCheck,
  "user-plus": UserPlus,
  "user-minus": UserMinus,
  "user-x": UserX,
  phone: Phone,
  mail: Mail,
  "message-square": MessageSquare,
  "message-circle": MessageCircle,
  send: Send,
  reply: Reply,
  forward: Forward,
  camera: Camera,
  video: Video,
  headphones: Headphones,
  gift: Gift,
  award: Award,
  trophy: Trophy,
  medal: Medal,

  // Financial Management
  wallet: Wallet,
  banknote: Banknote,
  coins: Coins,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "bar-chart": BarChart,
  "bar-chart-3": BarChart3,
  "pie-chart": PieChart,
  "line-chart": LineChart,
  activity: Activity,
  target: Target,
  percent: Percent,
  calculator: Calculator,
  receipt: Receipt,
  "file-text": FileText,
  "file-spreadsheet": FileSpreadsheet,
  download: Download,
  upload: Upload,
  printer: Printer,
  share: Share,

  // Staff Management
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  shield: Shield,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  fingerprint: Fingerprint,
  "qr-code": QrCode,
  smartphone: Smartphone,
  tablet: Tablet,
  monitor: Monitor,
  laptop: Laptop,

  // Reports & Analytics
  report: ReportIcon,
  export: ExportIcon,
  import: ImportIcon,
  "share-icon": ShareIcon,
  print: PrintIcon,
  "email-report": EmailReportIcon,

  // Communication
  chat: ChatIcon,
  message: MessageIcon,
  "phone-icon": PhoneIcon,
  "email-icon": EmailIcon2,
  "send-icon": SendIcon,
  "reply-icon": ReplyIcon,
  "forward-icon": ForwardIcon,
  "camera-icon": CameraIcon,
  "video-icon": VideoIcon,
  "headphones-icon": HeadphonesIcon,

  // Notifications
  notification: NotificationIcon,
  alert: AlertIcon,
  "info-icon": InfoIcon,
  success: SuccessIcon,
  error: ErrorIcon,
  "star-icon": StarIcon,
  "heart-icon": HeartIcon,
  "bookmark-icon": BookmarkIcon,

  // Actions
  edit: Edit,
  trash: Trash2,
  copy: Copy,
  save: Save,
  refresh: RefreshCw,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
  maximize: Maximize,
  minimize: Minimize,
  move: Move,
  crop: Crop,
  scissors: Scissors,

  // Status & Feedback
  check: Check,
  circle: Circle,
  square: Square,
  triangle: Triangle,
  hexagon: Hexagon,
  octagon: Octagon,

  // Time & Date
  "time-icon": TimeIcon2,
  date: DateIcon,
  days: DaysIcon,
  "watch-icon": WatchIcon,
  timer: Timer,
  sunrise: Sunrise,
  sunset: Sunset,
  moon: Moon,
  sun: Sun,

  // Location & Travel
  "location-icon": LocationIcon2,
  navigation: Navigation,
  compass: Compass,
  globe: Globe,
  map: Map,
  flag: Flag,
  anchor: Anchor,
  plane: Plane,
  train: Train,
  bus: Bus,
  "car-icon": CarIcon,
  "bike-icon": BikeIcon,
  ship: Ship,

  // Technology
  "wifi-icon": WifiIcon,
  bluetooth: Bluetooth,
  signal: Signal,
  battery: Battery,
  power: Power,
  zap: Zap,
  cpu: Cpu,
  "hard-drive": HardDrive,
  database: Database,
  server: Server,
  cloud: Cloud,
  "cloud-rain": CloudRain,
  "cloud-lightning": CloudLightning,
  "cloud-snow": CloudSnow,

  // Business & Commerce
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  store: Store,
  "package-icon": PackageIcon,
  truck: Truck,
  "box-icon": BoxIcon,
  archive: Archive,
  folder: Folder,
  "folder-open": FolderOpen,
  file: File,
  document: DocumentIcon,
  "file-image": FileImage,
  "file-video": FileVideo,
  "file-audio": FileAudio,
  "file-code": FileCode,

  // Security & Privacy
  security: SecurityIcon,
  "lock-icon": LockIcon,
  "unlock-icon": UnlockIcon,
  "key-icon": KeyIcon,
  "fingerprint-icon": FingerprintIcon,
  "qr-code-icon": QrCodeIcon,
  view: ViewIcon,
  hide: HideIcon,
  verify: VerifyIcon,
  block: BlockIcon,

  // Health & Wellness
  health: HealthIcon,
  fitness: FitnessIcon,
  gym: GymIcon,
  "coffee-icon": CoffeeIcon,
  food: FoodIcon,
  wine: Wine,
  beer: Beer,
  pill: Pill,
  stethoscope: Stethoscope,
  thermometer: Thermometer,

  // Entertainment
  "tv-icon": TvIcon,
  radio: Radio,
  audio: AudioIcon,
  speaker: Speaker,
  volume: Volume,
  "volume-x": VolumeX,
  "volume-1": Volume1,
  "volume-2": Volume2,
  play: Play,
  pause: Pause,
  "skip-back": SkipBack,
  "skip-forward": SkipForward,
  rewind: Rewind,
  "fast-forward": FastForward,
  shuffle: Shuffle,
  repeat: Repeat,
  music: Music,
  "video-icon-2": VideoIcon2,
  "camera-icon-2": CameraIcon2,
  image: Image,
  film: Film,
  dice: Dice1,
  puzzle: Puzzle,

  // Weather & Environment
  "sun-icon": SunIcon,
  "moon-icon": MoonIcon,
  "cloud-icon": CloudIcon,
  rain: RainIcon,
  snow: SnowIcon,
  lightning: LightningIcon,
  wind: Wind,
  temp: TempIcon,
  water: WaterIcon,
  umbrella: Umbrella,
  "snowflake-icon": SnowflakeIcon,
  leaf: Leaf,
  trees: Trees,
  flower: Flower,

  // Transportation
  "car-icon-2": CarIcon2,
  "bike-icon-2": BikeIcon2,
  "bus-icon": BusIcon,
  "train-icon": TrainIcon,
  "plane-icon": PlaneIcon,
  "ship-icon": ShipIcon,
  "truck-icon": TruckIcon,

  // Communication & Social
  "message-icon": MessageIcon2,
  "chat-icon": ChatIcon2,
  "phone-icon-2": PhoneIcon2,
  "mail-icon": MailIcon,
  "send-icon-2": SendIcon2,
  "reply-icon-2": ReplyIcon2,
  "forward-icon-2": ForwardIcon2,
  "share-icon-2": ShareIcon2,
  link: Link,
  "link-2": Link2,
  "external-link": ExternalLink,
  "at-sign": AtSign,
  hash: Hash,

  // Development & Tools
  code: Code,
  "git-branch": GitBranch,
  "git-commit": GitCommit,
  "git-merge": GitMerge,
  "git-pull-request": GitPullRequest,
  "git-compare": GitCompare,
  "git-fork": GitFork,
  terminal: Terminal,
  command: Command,
  "cpu-icon": CpuIcon,
  storage: StorageIcon,
  "database-icon": DatabaseIcon,
  "server-icon": ServerIcon,
  "cloud-icon-2": CloudIcon2,
  network: NetworkIcon,
  "bluetooth-icon": BluetoothIcon,
  "signal-icon": SignalIcon,
  "battery-icon": BatteryIcon,
  "power-icon": PowerIcon,
  "zap-icon": ZapIcon,

  // Miscellaneous
  "help-circle": HelpCircle,
  "info-icon-2": InfoIcon2,
  "alert-icon": AlertIcon2,
  "check-icon": CheckIcon,
  "x-icon": XIcon,
  "star-icon-2": StarIcon2,
  "heart-icon-2": HeartIcon2,
  "bookmark-icon-2": BookmarkIcon2,
  "flag-icon": FlagIcon,
  "award-icon": AwardIcon,
  "trophy-icon": TrophyIcon,
  "medal-icon": MedalIcon,
  "gift-icon": GiftIcon,
  "gift-box": GiftBoxIcon,
  "box-icon-2": BoxIcon2,
  "archive-icon": ArchiveIcon,
  "folder-icon": FolderIcon,
  "file-icon": FileIcon,
  "image-icon": ImageIcon,
  "video-icon-3": VideoIcon3,
  "code-icon": CodeIcon,
  "terminal-icon": TerminalIcon,
  "command-icon": CommandIcon,
  git: GitIcon,
  "commit-icon": CommitIcon2,
  "merge-icon": MergeIcon2,
  "pull-request": PullRequestIcon,
  "compare-icon": CompareIcon2,
  "fork-icon": ForkIcon2,
  data: DataIcon,
  "server-icon-2": ServerIcon2,
  "cloud-icon-3": CloudIcon3,
  "wifi-icon-2": WifiIcon2,
  "bluetooth-icon-2": BluetoothIcon2,
  "signal-icon-2": SignalIcon2,
  "battery-icon-2": BatteryIcon2,
  "power-icon-2": PowerIcon2,
  "zap-icon-2": ZapIcon2,
  "cpu-icon-2": CpuIcon2,
  "hard-drive-icon": HardDriveIcon,
  "database-icon-2": DatabaseIcon2,
  "server-icon-3": ServerIcon3,
  "cloud-icon-4": CloudIcon4,
  "wifi-icon-3": WifiIcon3,
  "bluetooth-icon-3": BluetoothIcon3,
  "signal-icon-3": SignalIcon3,
  "battery-icon-3": BatteryIcon3,
  "power-icon-3": PowerIcon3,
  "zap-icon-3": ZapIcon3,
}

export function Icon({
  name,
  size = 24,
  className,
  color,
  strokeWidth = 2,
  variant = "outline",
}: IconLibraryProps) {
  const IconComponent = iconMap[name]

  if (!IconComponent) {
    console.warn(`Icon "${name}" not found in icon library`)
    return null
  }

  const variantClasses = {
    outline: "",
    filled: "fill-current",
    duotone: "fill-current opacity-50",
  }

  return (
    <IconComponent
      size={size}
      className={cn(variantClasses[variant], className)}
      color={color}
      strokeWidth={strokeWidth}
    />
  )
}

// Export individual icons for direct use
export const Icons = {
  // Navigation & Core
  Dashboard: LayoutDashboard,
  Home,
  Menu,
  Close: X,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowUpDown,
  ArrowUp,
  ArrowDown,
  MoreHorizontal,
  MoreVertical,
  Plus,
  Minus,
  Search,
  Filter,
  Settings,
  User,
  LogOut,
  LogIn,
  Bell,
  Eye,
  EyeOff,

  // Inventory Management
  Package,
  Box,
  Bed,
  BedSingle,
  BedDouble,
  Hotel,
  Building,
  Building2,
  MapPin,
  Wifi,
  Snowflake,
  Tv,
  Droplets,
  Coffee,
  Utensils,
  Car,
  Bike,
  Dumbbell,
  Wrench,
  Hammer,

  // Booking & Reservations
  Calendar,
  CalendarDays,
  Clock,
  Watch,
  CheckCircle,
  XCircle,
  AlertCircle,
  Info,
  Star,
  Heart,
  Bookmark,
  Tag,
  Ticket,
  CreditCard,
  DollarSign,
  IndianRupee,
  Euro,
  PoundSterling,

  // Guest Services
  Users,
  UserCheck,
  UserPlus,
  UserMinus,
  UserX,
  Phone,
  Mail,
  MessageSquare,
  MessageCircle,
  Send,
  Reply,
  Forward,
  Camera,
  Video,
  Headphones,
  Gift,
  Award,
  Trophy,
  Medal,

  // Financial Management
  Wallet,
  Banknote,
  Coins,
  TrendingUp,
  TrendingDown,
  BarChart,
  BarChart3,
  PieChart,
  LineChart,
  Activity,
  Target,
  Percent,
  Calculator,
  Receipt,
  FileText,
  FileSpreadsheet,
  Download,
  Upload,
  Printer,
  Share,

  // Staff Management
  GraduationCap,
  BookOpen,
  Shield,
  Lock,
  Unlock,
  Key,
  Fingerprint,
  QrCode,
  Smartphone,
  Tablet,
  Monitor,
  Laptop,

  // Reports & Analytics
  Report: ReportIcon,
  Export: ExportIcon,
  Import: ImportIcon,
  ShareIcon,
  Print: PrintIcon,
  EmailReport: EmailReportIcon,

  // Communication
  Chat: ChatIcon,
  Message: MessageIcon,
  PhoneIcon,
  EmailIcon2,
  SendIcon,
  ReplyIcon,
  ForwardIcon,
  CameraIcon,
  VideoIcon,
  HeadphonesIcon,

  // Notifications
  Notification: NotificationIcon,
  Alert: AlertIcon,
  InfoIcon,
  Success: SuccessIcon,
  Error: ErrorIcon,
  StarIcon,
  HeartIcon,
  BookmarkIcon,

  // Actions
  Edit,
  Trash: Trash2,
  Copy,
  Save,
  Refresh: RefreshCw,
  RotateCcw,
  RotateCw,
  ZoomIn,
  ZoomOut,
  Maximize,
  Minimize,
  Move,
  Crop,
  Scissors,

  // Status & Feedback
  Check,
  Circle,
  Square,
  Triangle,
  Hexagon,
  Octagon,

  // Time & Date
  TimeIcon2,
  Date: DateIcon,
  Days: DaysIcon,
  WatchIcon,
  Timer,
  Sunrise,
  Sunset,
  Moon,
  Sun,

  // Location & Travel
  LocationIcon2,
  Navigation,
  Compass,
  Globe,
  Map,
  Flag,
  Anchor,
  Plane,
  Train,
  Bus,
  CarIcon,
  BikeIcon,
  Ship,

  // Technology
  WifiIcon,
  Bluetooth,
  Signal,
  Battery,
  Power,
  Zap,
  Cpu,
  HardDrive,
  Database,
  Server,
  CloudIcon,
  CloudRain,
  CloudLightning,
  CloudSnow,

  // Business & Commerce
  ShoppingCart,
  ShoppingBag,
  Store,
  PackageIcon,
  Truck,
  BoxIcon,
  Archive,
  Folder,
  FolderOpen,
  File,
  Document: DocumentIcon,
  FileImage,
  FileVideo,
  FileAudio,
  FileCode,

  // Security & Privacy
  Security: SecurityIcon,
  LockIcon,
  UnlockIcon,
  KeyIcon,
  FingerprintIcon,
  QrCodeIcon,
  View: ViewIcon,
  Hide: HideIcon,
  Verify: VerifyIcon,
  Block: BlockIcon,

  // Health & Wellness
  Health: HealthIcon,
  Fitness: FitnessIcon,
  Gym: GymIcon,
  CoffeeIcon,
  Food: FoodIcon,
  Wine,
  Beer,
  Pill,
  Stethoscope,
  Thermometer,

  // Entertainment
  TvIcon,
  Radio,
  Audio: AudioIcon,
  Speaker,
  Volume,
  VolumeX,
  Volume1,
  Volume2,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Shuffle,
  Repeat,
  Music,
  VideoIcon2,
  CameraIcon2,
  Image,
  Film,
  Dice: Dice1,
  Puzzle,

  // Weather & Environment
  SunIcon,
  MoonIcon,
  Cloud: CloudIcon,
  Rain: RainIcon,
  Snow: SnowIcon,
  Lightning: LightningIcon,
  Wind,
  Temp: TempIcon,
  Water: WaterIcon,
  Umbrella,
  SnowflakeIcon,
  Leaf,
  Trees,
  Flower,

  // Transportation
  CarIcon2,
  BikeIcon2,
  BusIcon,
  TrainIcon,
  PlaneIcon,
  ShipIcon,
  TruckIcon,

  // Communication & Social
  MessageIcon2,
  ChatIcon2,
  PhoneIcon2,
  MailIcon,
  SendIcon2,
  ReplyIcon2,
  ForwardIcon2,
  ShareIcon2,
  Link,
  Link2,
  ExternalLink,
  AtSign,
  Hash,

  // Development & Tools
  Code,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  GitCompare,
  GitFork,
  Terminal,
  Command,
  CpuIcon,
  Storage: StorageIcon,
  DatabaseIcon,
  ServerIcon,
  Cloud2: CloudIcon2,
  Network: NetworkIcon,
  BluetoothIcon,
  SignalIcon,
  BatteryIcon,
  PowerIcon,
  ZapIcon,

  // Miscellaneous
  HelpCircle,
  InfoIcon2,
  AlertIcon2,
  CheckIcon,
  XIcon,
  StarIcon2,
  HeartIcon2,
  BookmarkIcon2,
  FlagIcon,
  AwardIcon,
  TrophyIcon,
  MedalIcon,
  GiftIcon,
  GiftBox: GiftBoxIcon,
  BoxIcon2,
  ArchiveIcon,
  FolderIcon,
  FileIcon,
  ImageIcon,
  VideoIcon3,
  CodeIcon,
  TerminalIcon,
  CommandIcon,
  Git: GitIcon,
  CommitIcon2,
  MergeIcon2,
  PullRequest: PullRequestIcon,
  CompareIcon2,
  ForkIcon2,
  Data: DataIcon,
  ServerIcon2,
  Cloud3: CloudIcon3,
  WifiIcon2,
  BluetoothIcon2,
  SignalIcon2,
  BatteryIcon2,
  PowerIcon2,
  ZapIcon2,
  CpuIcon2,
  HardDriveIcon,
  DatabaseIcon2,
  ServerIcon3,
  Cloud4: CloudIcon4,
  WifiIcon3,
  BluetoothIcon3,
  SignalIcon3,
  BatteryIcon3,
  PowerIcon3,
  ZapIcon3,
}
